---
title: "Zpětká vazba z kurzu, Discover júlový turnus"
output: 
  html_document: 
    theme: journal
    toc: yes
---

# ```r ikurz ```

``` {r KnitrPrep, cache=FALSE,include=FALSE}
library(knitr)
library(Cairo)
# set up graphing:
opts_chunk$set(echo=FALSE, dev='CairoPNG', warning=FALSE)
# make relative references work - change this to project directory
opts_knit$set(root.dir='~/github/experiments/d15eval/')
```

``` {r Load tools library from anywhere, include=FALSE, echo=FALSE}
# install.packages(devtools)
# library(devtools)
# install_github('pbtools','petrbouchal')
library(pbtools)
```

```{r LoadDataKurzy, include=F, echo=F}
kurzy3 <- kurzy_long %>% 
  filter(variable %in% dnyvtydnu,
         !is.na(kurz)) %>% 
  mutate(value=as.numeric(value),
         variable = droplevels(variable),
         variable = factor(variable, levels=dnyvtydnu))

kurzy4 <- kurzy3 %>% 
  group_by(variable, kurz, kurzslot) %>% 
  summarise(value = mean(value, na.rm = T))

kurzy5 <- kurzy3 %>% 
  group_by(variable, kurz) %>% 
  summarise(value = mean(value, na.rm = T))

kurzy5$kurzslot <- "oba"
kurzyplot <- rbind(kurzy4, kurzy5)

kurzyplot <- kurzyplot %>% 
  group_by(kurz, variable) %>% 
  mutate(pocetslotu = n()-1)

kurzplot <- filter(kurzyplot, kurz==ikurz)
```

```{r PrepTheme, echo=F, include=F}

loadcustomthemes(fontfamily = "Gill Sans MT")
theme_discover <- theme(panel.grid.minor=element_line(color="grey96", size=.5),
                        panel.grid.major=element_line(color="white", size=.75),
                        strip.text = element_text(size=12, color="grey20"),
                        panel.background = element_rect(fill="grey96"),
                        axis.text.x = element_text(size=11),
                        strip.background=element_rect(fill="grey96"))


```


## Hodnocení kurzu

```{r CalcAve, echo=F, include=F}
kurzplot <- if(mean(kurzplot$pocetslotu)==2) { kurzplot } else { kurzplot[kurzplot$kurzslot!="oba",] }
print(kurzplot)
```


```{r}
hodavg <- kurzplot %>% group_by(kurzslot) %>% summarise(prumer=mean(value))
names(hodavg) <- c("Blok setkání","Průměrná známka")
```

Průměrná známka: `r knitr::kable(hodavg, digits=2)  `

### Hodnocení po dnech

```{r GrafHodnoceni}
ggplot(kurzplot, aes(x=variable, y=value, group=kurzslot, colour=kurzslot)) +
  geom_line(size=1) +
  geom_point(size=3, pch=19) +
  scale_y_continuous(limits=c(1,3)) +
  scale_colour_manual(values=c("A"="lightgoldenrod1","B"="aquamarine3","oba"="black")) +
  geom_text(aes(label=formatC(value, digits=2, format="f"),
                y=value+.2),
            size=3, colour="grey40",fontface="bold",
            data=kurzplot[kurzplot$kurzslot==unique(kurzplot$kurzslot)[1],]) +
  theme_discover

```


## Analysis
